### ISSUE TITLE
py-kms on W2012R2 as service start and then stop

### ISSUE THREAD

**Issue by ssv1907** [SystemRage/py-kms#71]
Hello
Installed py-kmc as written on the wiki (https://github.com/SystemRage/py-kms/issues/2). Copied pywintypes38.dll to the Win32 folder https://github.com/SystemRage/py-kms/issues/47. python-3.8.3-amd64 and pywin32-228.win-amd64-py3.8 also installed. Service py-kms installed successeful but it run and stop (((. What am I doing wrong? No errors in Windows Event and Path to Executable in service py-kmc is "C:\Python38\lib\site-packages\win32\PythonService.exe"

**Comment by Simonmicro** [comment]
- Can you post any log files?
- Can you execute it manually (and therefore check for any errors)?
- Are you sure Python is available inside the service environment (idk how that part of Windows really works)?
- Did you restart the server since you installed Python and everything else?
- Just to be sure: You did not just download any file named like `pywintypes38.dll` from the internet and used it - instead you really used the .dll from your server?

**Comment by SystemRage** [comment]
Your service stops maybe because: https://github.com/SystemRage/py-kms/issues/58#issuecomment-616227358
try to auto-patch as described and give feedback if works (if it's the real problem i can later try to correct)

**Comment by ssv1907** [comment]
> Your service stops maybe because: [#58 (comment)](https://github.com/SystemRage/py-kms/issues/58#issuecomment-616227358)
> try to auto-patch as described and give feedback if works (if it's the real problem i can later try to correct)

Bingo!!! It's work for me! Thanks
